# Generated by Django 5.2.1 on 2025-05-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordertracker_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracker',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='order.order'),
        ),
    ]
